// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  // Migrations لازم يعدّوا باتصال مباشر (مش عبر pgbouncer transaction-mode) —
  // pgbouncer transaction pooling ماعندوش الجلسة الثابتة اللي Migrate محتاجها
  // (advisory locks + prepared statements). الاستعلامات الفعلية بالتطبيق (src/lib/prisma.ts)
  // بتستخدم DATABASE_URL (الـpooler) مباشرة، مش الملف ده.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
